server
{
    listen 80;
    listen [::]:80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server
{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name localhost;
    ssl_certificate /etc/nginx/certs/transcendence.crt; 
    ssl_certificate_key /etc/nginx/certs/transcendence.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location /
    {
        proxy_pass http://front:3003;

    }
    location /api/auth/
    {
        proxy_pass http://auth:3004/api/auth/;
    }
    location /api/chat/
    {
        proxy_pass http://chat:3001/api/chat/;
    }
    location /api/users/
    {
        proxy_pass http://user:3002/api/users/;
    }
    location /api/listings/
    {
        proxy_pass http://listings:3005/api/listings/;
    }

}
