



# POST http://localhost:3004/api/auth/signup
# Content-Type: application/json

# {
#   "email": "user@example.com",
#   "password": "MyPassword123"
# }


# POST http://localhost:3004/api/auth/login
# Content-Type: application/json

# {
#   "identifier": "user@example.com",
#   "password": "MyPassword123"
# }



### Upload Avatar


### Upload Avatar
DELETE  http://localhost:3002/api/users/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjpudWxsLCJpYXQiOjE3NzI1ODM2NjksImV4cCI6MTc3MzE4ODQ2OX0.EUT_Qldage4M1D_5Ed8EswuNDgjM1Wve-gNwuSnwjE0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test_image.jpg"
Content-Type: image/jpeg

< /home/younesoun/Downloads/test_image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--