



# POST http://localhost:3004/api/auth/signup
# Content-Type: application/json

# {
#   "email": "user@example.com",
#   "password": "MyPassword123"
# }


# POST http://localhost:3004/api/auth/login
# Content-Type: application/json

# {
#   "identifier": "user@example.com",
#   "password": "MyPassword123"
# }




POST http://localhost:3005/api/listings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjpudWxsLCJpYXQiOjE3NzI1ODM2NjksImV4cCI6MTc3MzE4ODQ2OX0.EUT_Qldage4M1D_5Ed8EswuNDgjM1Wve-gNwuSnwjE0
Content-Type: application/json

{
  "title": "Cozy Apartment near Campus",
  "location": "Paris 13e",
  "price": 650,
  "currency": "EUR",
  "availableDate": "2026-02-01",
  "spotsTotal": 2,
  "spotsFilled": 0,
  "description": "Nice apartment with balcony and great view...",
  "hasWifi": true,
  "hasKitchen": true,
  "hasLaundry": false,
  "hasMetroNearby": true,
  "hasGarden": false,
  "hasParking": true,
  "petsOK": false,
  "hasGym": false,
  "hasAC": true,
  "isSecure": true
}